# Generated by Django 5.1.6 on 2025-03-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=50)),
                ('equipo_local', models.CharField(max_length=100)),
                ('equipo_visitante', models.CharField(max_length=100)),
                ('resultado_local', models.IntegerField(blank=True, null=True)),
                ('resultado_visitante', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('imagen_local', models.URLField()),
                ('imagen_visitante', models.URLField()),
            ],
        ),
    ]
